version: '3.8'
services:
  backend:
    image: node:12-alpine
    ports:
      - '8080:80'
  frontend:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
